In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns 
%matplotlib inline

In [3]:
data = pd.read_csv('NIGERIA_DEMOGRAPHICS_DATA.csv')
data.head()

,Timestamp,Are you a Nigerian?,Gender,Age Group,Are you married?,Do you have kids?,Where do you live?,What part of your state do you live in?,Occupation,Are you Happy with your job?,...,Do you think it is enough for you and your family?,What are your other sources of income?,Do you pay your tax?,What is your largest form of expense,"If there was one thing you really wanted to own, what would that be?",How much do you think you earn from all other sources of income in a month,"On an average, how much do you think you spend in a month?",Do you think Nigeria can get better?,"In a short sentence, describe your government",Please fill your email if you want to be notified once this research is completed.
0,10/13/2019 17:45:01,NaN,Female,18 – 25,No,No,Lagos,Rural,NaN,No,...,No,NaN,No,Feeding,A Company,NaN,25000,Yes,Frustrating,ikeoluwa933@gmail.com
1,10/13/2019 18:13:59,NaN,Female,18 – 25,No,No,Lagos,Rural,No Job,No,...,No,Free Lancing,No,Transportation,A House,18000.0,20000,Yes,"Greedy, self centered and dull",NaN
2,10/13/2019 20:11:39,NaN,Male,36 – 45,Yes,Yes,Lagos,City,Financial Services,Yes,...,No,Free Lancing,Yes,School Fees,A Company,40000.0,140000,Yes,Our government do not care about what the mass...,olanrewaju1temitayo@gmail.com
3,10/13/2019 20:17:57,NaN,Female,26 – 35,No,No,Lagos,City,Business,Yes,...,No,Buying and Selling,Yes,Transportation,Money,500000.0,100000,Yes,There is discrepancy in Nigeria's governance. ...,adewunmi.fatoki@gmail.com
4,10/14/2019 6:24:13,NaN,Male,26 – 35,No,No,Lagos,Rural,Engineering,Yes,...,Yes,Formal Job,Yes,Transportation,A Company,0.0,60000,Yes,It is a corrupt one lead by inconsiderate fell...,Johnnyark9@gmail.com

In [4]:
#To call all columns since it wasnt all that appeared in the data set
pd.set_option('display.max_columns', None)
data.head()

,Timestamp,Are you a Nigerian?,Gender,Age Group,Are you married?,Do you have kids?,Where do you live?,What part of your state do you live in?,Occupation,Are you Happy with your job?,Is this your primary source of income?,What is your steady/constant income range in a month?,Do you think it is enough for you and your family?,What are your other sources of income?,Do you pay your tax?,What is your largest form of expense,"If there was one thing you really wanted to own, what would that be?",How much do you think you earn from all other sources of income in a month,"On an average, how much do you think you spend in a month?",Do you think Nigeria can get better?,"In a short sentence, describe your government",Please fill your email if you want to be notified once this research is completed.
0,10/13/2019 17:45:01,NaN,Female,18 – 25,No,No,Lagos,Rural,NaN,No,No,Below 5000,No,NaN,No,Feeding,A Company,NaN,25000,Yes,Frustrating,ikeoluwa933@gmail.com
1,10/13/2019 18:13:59,NaN,Female,18 – 25,No,No,Lagos,Rural,No Job,No,No,"11,000 – 20,000",No,Free Lancing,No,Transportation,A House,18000.0,20000,Yes,"Greedy, self centered and dull",NaN
2,10/13/2019 20:11:39,NaN,Male,36 – 45,Yes,Yes,Lagos,City,Financial Services,Yes,Yes,"110,000 – 200,000",No,Free Lancing,Yes,School Fees,A Company,40000.0,140000,Yes,Our government do not care about what the mass...,olanrewaju1temitayo@gmail.com
3,10/13/2019 20:17:57,NaN,Female,26 – 35,No,No,Lagos,City,Business,Yes,Yes,"201,000 – 300,000",No,Buying and Selling,Yes,Transportation,Money,500000.0,100000,Yes,There is discrepancy in Nigeria's governance. ...,adewunmi.fatoki@gmail.com
4,10/14/2019 6:24:13,NaN,Male,26 – 35,No,No,Lagos,Rural,Engineering,Yes,Yes,"110,000 – 200,000",Yes,Formal Job,Yes,Transportation,A Company,0.0,60000,Yes,It is a corrupt one lead by inconsiderate fell...,Johnnyark9@gmail.com

In [5]:
#Renaming columns because they look too lengthy in words
data.columns = ['date', 'Nigerian citzen', 'gender', 'age group', 'married', 'parenting', 'location', 'region','occupation', 'job_satiated', 'primary income source?','monthly salary range', 'is salary family sufficient?', 'other income source','tax compliant?', 'largest expense', 'dream property', 'other income earnings', 'monthly expenses', 'can Nigeria become better', 'describe government', 'email']
data.head()

,date,Nigerian citzen,gender,age group,married,parenting,location,region,occupation,job_satiated,primary income source?,monthly salary range,is salary family sufficient?,other income source,tax compliant?,largest expense,dream property,other income earnings,monthly expenses,can Nigeria become better,describe government,email
0,10/13/2019 17:45:01,NaN,Female,18 – 25,No,No,Lagos,Rural,NaN,No,No,Below 5000,No,NaN,No,Feeding,A Company,NaN,25000,Yes,Frustrating,ikeoluwa933@gmail.com
1,10/13/2019 18:13:59,NaN,Female,18 – 25,No,No,Lagos,Rural,No Job,No,No,"11,000 – 20,000",No,Free Lancing,No,Transportation,A House,18000.0,20000,Yes,"Greedy, self centered and dull",NaN
2,10/13/2019 20:11:39,NaN,Male,36 – 45,Yes,Yes,Lagos,City,Financial Services,Yes,Yes,"110,000 – 200,000",No,Free Lancing,Yes,School Fees,A Company,40000.0,140000,Yes,Our government do not care about what the mass...,olanrewaju1temitayo@gmail.com
3,10/13/2019 20:17:57,NaN,Female,26 – 35,No,No,Lagos,City,Business,Yes,Yes,"201,000 – 300,000",No,Buying and Selling,Yes,Transportation,Money,500000.0,100000,Yes,There is discrepancy in Nigeria's governance. ...,adewunmi.fatoki@gmail.com
4,10/14/2019 6:24:13,NaN,Male,26 – 35,No,No,Lagos,Rural,Engineering,Yes,Yes,"110,000 – 200,000",Yes,Formal Job,Yes,Transportation,A Company,0.0,60000,Yes,It is a corrupt one lead by inconsiderate fell...,Johnnyark9@gmail.com

In [6]:
#To rearrange columns
cols = list(data.columns.values)
data = data[cols[0:11] + cols[12:17] + [cols[11]] + cols[17:22]]
data.head()

,date,Nigerian citzen,gender,age group,married,parenting,location,region,occupation,job_satiated,primary income source?,is salary family sufficient?,other income source,tax compliant?,largest expense,dream property,monthly salary range,other income earnings,monthly expenses,can Nigeria become better,describe government,email
0,10/13/2019 17:45:01,NaN,Female,18 – 25,No,No,Lagos,Rural,NaN,No,No,No,NaN,No,Feeding,A Company,Below 5000,NaN,25000,Yes,Frustrating,ikeoluwa933@gmail.com
1,10/13/2019 18:13:59,NaN,Female,18 – 25,No,No,Lagos,Rural,No Job,No,No,No,Free Lancing,No,Transportation,A House,"11,000 – 20,000",18000.0,20000,Yes,"Greedy, self centered and dull",NaN
2,10/13/2019 20:11:39,NaN,Male,36 – 45,Yes,Yes,Lagos,City,Financial Services,Yes,Yes,No,Free Lancing,Yes,School Fees,A Company,"110,000 – 200,000",40000.0,140000,Yes,Our government do not care about what the mass...,olanrewaju1temitayo@gmail.com
3,10/13/2019 20:17:57,NaN,Female,26 – 35,No,No,Lagos,City,Business,Yes,Yes,No,Buying and Selling,Yes,Transportation,Money,"201,000 – 300,000",500000.0,100000,Yes,There is discrepancy in Nigeria's governance. ...,adewunmi.fatoki@gmail.com
4,10/14/2019 6:24:13,NaN,Male,26 – 35,No,No,Lagos,Rural,Engineering,Yes,Yes,Yes,Formal Job,Yes,Transportation,A Company,"110,000 – 200,000",0.0,60000,Yes,It is a corrupt one lead by inconsiderate fell...,Johnnyark9@gmail.com

In [7]:
#checking the shape of the data frame
data.shape

(303, 22)

In [8]:
data.columns

Index(['date', 'Nigerian citzen', 'gender', 'age group', 'married',
       'parenting', 'location', 'region', 'occupation', 'job_satiated',
       'primary income source?', 'is salary family sufficient?',
       'other income source', 'tax compliant?', 'largest expense',
       'dream property', 'monthly salary range', 'other income earnings',
       'monthly expenses', 'can Nigeria become better', 'describe government',
       'email'],
      dtype='object')

In [9]:
data.dtypes

date                             object
Nigerian citzen                  object
gender                           object
age group                        object
married                          object
parenting                        object
location                         object
region                           object
occupation                       object
job_satiated                     object
primary income source?           object
is salary family sufficient?     object
other income source              object
tax compliant?                   object
largest expense                  object
dream property                   object
monthly salary range             object
other income earnings           float64
monthly expenses                  int64
can Nigeria become better        object
describe government              object
email                            object
dtype: object

In [10]:
#check for missing values
data.isnull().sum()

date                              0
Nigerian citzen                  15
gender                            0
age group                         0
married                           0
parenting                         0
location                          0
region                            0
occupation                        1
job_satiated                      0
primary income source?            0
is salary family sufficient?      0
other income source               1
tax compliant?                    0
largest expense                   0
dream property                    0
monthly salary range              0
other income earnings             1
monthly expenses                  0
can Nigeria become better         0
describe government               1
email                           122
dtype: int64

In [11]:
#Identifying the unique numbers of values of the dataset
data.nunique()

date                            303
Nigerian citzen                   2
gender                            3
age group                         5
married                           2
parenting                         2
location                         20
region                            4
occupation                       13
job_satiated                      2
primary income source?            2
is salary family sufficient?      2
other income source              17
tax compliant?                    2
largest expense                   9
dream property                    6
monthly salary range             10
other income earnings            47
monthly expenses                 54
can Nigeria become better         2
describe government             268
email                           179
dtype: int64

In [12]:
#viewing the data statistics 
data.describe()

       other income earnings  monthly expenses
count           3.020000e+02      3.030000e+02
mean            6.627668e+07      1.650782e+08
std             8.124313e+08      2.872421e+09
min             0.000000e+00      0.000000e+00
25%             5.500000e+01      2.000000e+04
50%             1.500000e+04      4.700000e+04
75%             5.000000e+04      8.000000e+04
max             1.000000e+10      5.000000e+10

In [13]:
#finding out the correlation between the features
corr = data.corr()
corr.shape

(2, 2)

In [14]:
data['age group'].value_counts()

18 – 25    181
26 – 35    104
36 – 45     13
46 – 55      4
56 – 65      1
Name: age group, dtype: int64

In [15]:
#To Inquire Nigerians earnings in a year
data['monthly salary range'].value_counts()

21,000 – 50,000      82
110,000 – 200,000    37
81,000 – 100,000     35
51,000 – 80,000      33
11,000 – 20,000      29
Below 5000           29
201,000 – 300,000    23
5000 – 10,000        18
301,000 – 500,000     9
500,000 – above       8
Name: monthly salary range, dtype: int64

In [17]:
data['monthly salary range']= data['monthly salary range'].replace('Below 5000', 2500)
data['monthly salary range']= data['monthly salary range'].replace('11,000-20,000', 15500)
data['monthly salary range']= data['monthly salary range'].replace('110,000-200,000', 155000)
data['monthly salary range']= data['monthly salary range'].replace('201,000-300,000', 255000)

In [23]:
data['monthly salary range']

0                   2500
1        11,000 – 20,000
2      110,000 – 200,000
3      201,000 – 300,000
4      110,000 – 200,000
5        51,000 – 80,000
6      201,000 – 300,000
7        11,000 – 20,000
8        21,000 – 50,000
9       81,000 – 100,000
10       51,000 – 80,000
11       51,000 – 80,000
12         5000 – 10,000
13       21,000 – 50,000
14     110,000 – 200,000
15     201,000 – 300,000
16       51,000 – 80,000
17       11,000 – 20,000
18       51,000 – 80,000
19     110,000 – 200,000
20     201,000 – 300,000
21     201,000 – 300,000
22       11,000 – 20,000
23     110,000 – 200,000
24       11,000 – 20,000
25       21,000 – 50,000
26       21,000 – 50,000
27       11,000 – 20,000
28                  2500
29       21,000 – 50,000
             ...
273    110,000 – 200,000
274    201,000 – 300,000
275      21,000 – 50,000
276        5000 – 10,000
277      21,000 – 50,000
278                 2500
279      21,000 – 50,000
280      11,000 – 20,000
281      21,000 – 50,000
282    110,000 – 200,000
283      500,000 – above
284      51,000 – 80,000
285      51,000 – 80,000
286     81,000 – 100,000
287                 2500
288                 2500
289    201,000 – 300,000
290                 2500
291        5000 – 10,000
292    110,000 – 200,000
293    110,000 – 200,000
294      21,000 – 50,000
295    201,000 – 300,000
296      21,000 – 50,000
297        5000 – 10,000
298      51,000 – 80,000
299      51,000 – 80,000
300    301,000 – 500,000
301      21,000 – 50,000
302      51,000 – 80,000
Name: monthly salary range, Length: 303, dtype: object

In [ ]:
#plotting the heatmap correlation between features
plt.figure()